name: Generate, Test and Push API Definition

on:
   pull_request:
   workflow_dispatch:

jobs:
   generate-test-push:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Deploy API
            run: ./bin/deployapi.sh latest
