name: Lint and Test OpenAPI document

on:
   workflow_dispatch:

jobs:
   lint:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
        - 
         name: Lint API Definition
         uses: stoplightio/spectral-action@latest
         with:
            file_glob: 'openapi_schema.json'