name: Lint and Test OpenAPI document

on:
   pull_request: 

jobs:
   lint:
      runs-on: ubuntu-latest
      steps:
      - 
         name: Checkout
         uses: actions/checkout@v4
      -
         name: Setup Python
         uses: actions/setup-python@v2
         with:
            python-version: 3.10.5
            cache: pip
      -
         name: Install dependencies
         run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      -
         name: Generating OpenAPI document
         run: python3 extract-openapi.py main:app --out openapi.json
      - 
         name: Lint API Definition with Spectral
         uses: stoplightio/spectral-action@latest
         with:
            file_glob: 'openapi.json'
      -
         name: Lint API Definition with Redocly
         run: docker run --rm -v $PWD:/spec redocly/cli lint openapi.json