name: CI

on:
   pull_request:
   workflow_dispatch:

jobs:
   build-test-push:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         packages: write
         pull-requests: write
      continue-on-error: false
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         -
            name: Generating OpenAPI document
            run: python3 extract-openapi.py main:app --out openapi.json
         -
            name: Convert to Tyk OAS API Definition
            run: |
               #!/bin/bash
               body=$(<openapi.json)
               wget --method=POST http://tyk-dashboard.org/api/apis/oas/import --header='Authorization: ${{ secrets.TYK_APIKEY }}' --header='Content-Type: text/plain' --body-data="$body" -O res.json
               api_id=$(cat res.json | jq -r '.ID')

               echo "# "
               echo "# Temporary API ID $api_id ..."
               echo "# "

               echo "# "
               echo "# Retrieve API Definition JSON..."
               echo "# "
               wget --method=GET http://tyk-dashboard.org/api/apis/oas/$api_id --header 'Authorization: ${{ secrets.TYK_APIKEY }}' --header 'Content-Type: text/plain' -O res.json

               cat res.json | jq '.' > tyk_apidefinition.json

               echo "# "
               echo "# Remove Temporary API $api_id ..."
               echo "# "
               wget --method=DELETE http://tyk-dashboard.org/api/apis/oas/$api_id --header 'Authorization: ${{ secrets.TYK_APIKEY }}' -O res.json

               rm res.json

               echo "# "
               echo "# Generated API Definition ..."
               echo "# "
               cat tyk_apidefinition.json
         - 
            name: Lint API Definition
            uses: stoplightio/spectral-action@v0.8.11
            with:
               file_glob: 'tyk_apidefinition.json'
         -
            name: Build
            uses: docker/build-push-action@v5
            with:
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
               platforms: linux/amd64
         -
            name: Commit files
            id: commit
            shell: bash
            run: |
               git config --local user.email "action@github.com"
               git config --local user.name "github-actions"
               git add tyk_apidefinition.json
               if [-z "$(git status --porcelain)"]; then
                  echo "::set-output name=push::false"
               else
                  git commit -m "API Definition updated" -a
                  echo "::set-output name=push::true"
               fi
         - 
            name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
         -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
         -
            name: Push the API Definition to OCI
            run: oras push registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/apis:fastapi-httpbin-${{ env.DOCKER_METADATA_OUTPUT_VERSION }} tyk_apidefinition.json:application/json
