name: CI

env:
   REGISTRY: "caroltyk"
   APP_NAME: "fastapi-httpbin"
   API_REGISTRY: "apis"

on:
   push:
      tags: '*'

jobs:
   build-test-push:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: caroltyk/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
         -
            name: Extract OpenAPI
            run: python extract-openapi.py main:app --out openapi.json
         -
            name: Push the OpenAPI to OCI
            run: oras push registry-1.docker.io/caroltyk/apis:fastapi-httpbin-${{ env.DOCKER_METADATA_OUTPUT_VERSION }} openapi.json:application/json
