name: Run tests on PRs

on:
   pull_request:
   workflow_dispatch:

jobs:
   build-test:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         pull-requests: write
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
               cache: pip
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         - 
            name: Lint
            run: |
                 echo "** Lint code here **"
         -
            name: Build
            uses: docker/build-push-action@v5
            with:
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
               platforms: linux/amd64
         - 
            name: Testing
            run: |
                  echo "** Run tests here **"
         -
            name: Generating OpenAPI document
            run: |
               python3 extract-openapi.py main:app --out temp_openapi.json
               cat temp_openapi.json
         - 
            name: Lint API Definition with Spectral
            uses: stoplightio/spectral-action@v0.8.11
            with:
               file_glob: 'temp_openapi.json'
            continue-on-error: true
         -
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint temp_openapi.json
            continue-on-error: true
