name: Run tests on PRs

on:
   pull_request:
   workflow_dispatch:

jobs:
   build-test-push:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         packages: write
         pull-requests: write
      continue-on-error: false
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         -
            name: Generating OpenAPI document
            run: python3 extract-openapi.py main:app --out openapi.json
         - 
            name: Lint API Definition
            uses: stoplightio/spectral-action@v0.8.11
            with:
               file_glob: 'openapi.json'
         -
            name: Commit files
            id: commit
            shell: bash
            run: |
               git config --local user.email "action@github.com"
               git config --local user.name "github-actions"
               git add openapi.json
               if [-z "$(git status --porcelain)"]; then
                  echo "::set-output name=push::false"
               else
                  git commit -m "API Definition updated" -a
                  echo "::set-output name=push::true"
               fi
         - 
            name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}