name: Run tests on PRs

on:
   pull_request:
   workflow_dispatch:

jobs:
   build-test:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         pull-requests: write
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
               cache: pip
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         - 
            name: Lint
            run: |
                 echo "** Lint code here **"
         - 
            name: Testing
            run: |
                  echo "** Run tests here **"
         -
            name: Generating OpenAPI document
            run: python3 extract-openapi.py main:app --out openapi.json
         - 
            name: Lint API Definition with Spectral
            uses: stoplightio/spectral-action@latest
            with:
               file_glob: 'openapi.json'
         -
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint openapi.json
         -
            name: Commit files
            id: commit
            shell: bash
            run: |
               git config --local user.email "action@github.com"
               git config --local user.name "github-actions"
               git add openapi.json
               if [-z "$(git status --porcelain)"]; then
                  echo "::set-output name=push::false"
               else
                  git commit -m "API Definition updated" -a
                  echo "::set-output name=push::true"
               fi
         - 
            name: Push changes
            if: steps.commit.outputs.push == 'true'
            uses: ad-m/github-push-action@master
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}