name: Run tests on PRs

on:
   pull_request:
   workflow_dispatch:

jobs:
   build-test:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         pull-requests: write
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
               cache: pip
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         - 
            name: Lint
            run: |
                 echo "** Lint code here **"
         -
            name: Build
            run: |
                 echo "** Build code here **"
         - 
            name: Testing
            run: |
                  echo "** Run tests here **"
         -
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint openapi_schema.json --config openapi_rules.yaml
