name: Test and Lint PR

on:
   pull_request:
      types: 
         - opened
         - edited
         - synchronize
         - reopened
   workflow_dispatch:
   workflow_call:

jobs:
   lint:
      name: Lint API definition
      runs-on: ubuntu-latest
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint openapi_schema.json --config openapi_rules.yaml --format=github-actions
