name: Run tests on PRs

on:
   pull_request:
      types: 
         - opened
         - edited
         - reopened
   workflow_dispatch:

jobs:
   build-test:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         pull-requests: read
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         - 
            name: Lint
            run: |
                 echo "** Lint code here **"
         -
            name: Build
            run: |
                 echo "** Build code here **"
         - 
            name: Testing
            run: |
                  echo "** Run tests here **"
         -
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint openapi_schema.json --config openapi_rules.yaml --format=github-actions
