name: CI and release

on:
   workflow_dispatch:
   push:
      tags:
         - "*"

jobs:
   build-test-push:
      runs-on: ubuntu-latest
      permissions:
         contents: write
         packages: write
         pull-requests: write
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Setup Python
            uses: actions/setup-python@v2
            with:
               python-version: 3.10.5
         -
            name: Install dependencies
            run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-httpbin
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         - 
            name: Lint API Definition with Redocly
            run: docker run --rm -v $PWD:/spec redocly/cli lint openapi_schema.json --config openapi_rules.yaml --format=github-actions
         -
            name: Build
            uses: docker/build-push-action@v5
            with:
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
               platforms: linux/amd64
         -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
         -
            name: Push the API Definition to OCI
            run: oras push registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/apis:fastapi-httpbin-${{ env.DOCKER_METADATA_OUTPUT_VERSION }} openapi_schema.json:application/json
