name: Build and Push Tags

on:
   workflow_call:
   workflow_dispatch:
   push:
      tags:
         - "*"

jobs:
   test:
      name: Test and Lint
      uses: ./.github/workflows/pr_test.yml

   build-push:
      name: Build docker containers
      runs-on: ubuntu-latest
      permissions:
         contents: write
         packages: write
         pull-requests: write
      env:
         apiName: oas-httpbin
      steps:
         -
            name: Checkout
            uses: actions/checkout@v4
         -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
         -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
         -
            name: Extract metadata for the Docker image
            id: meta
            uses: docker/metadata-action@v5
            with:
               images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.apiName }}
         -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
         -
            name: Docker Build Push
            uses: docker/build-push-action@v5
            with:
               push: true
               tags: ${{ steps.meta.outputs.tags }}
               labels: ${{ steps.meta.outputs.labels }}
               platforms: linux/amd64
         -
            name: Setup ORAS
            uses: oras-project/setup-oras@v1
         -
            name: Push the API Definition to OCI
            run: oras push registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/apis:${{ env.apiName }}-${{ env.DOCKER_METADATA_OUTPUT_VERSION }} openapi_schema.json:application/json