name: Test workflow trigger

on:
   workflow_dispatch: 

jobs:
   test-trigger:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         actions: write
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4

         -  
            name: Trigger workflow
            uses: octokit/action@v2
            with:
               action: workflow_dispatch
               workflow: trigger
               repo: caroltyk/tyk-apiops-demo
               inputs: |
                  payload: '{"key": "value"}'