name: Test workflow trigger

on:
   workflow_dispatch: 

jobs:
   test-trigger:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         actions: write
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4

         # Install Node 20
         - 
            uses: actions/setup-node@v4
            with:
               node-version: 20
         -
            run: npm install @octokit/action
         
         # Node.js script can be anywhere. A good convention is to put local GitHub Actions
         # into the `.github/actions` folder
         - 
            run: node .github/actions/release-script.js
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}