name: Test workflow trigger

on:
   workflow_dispatch: 

jobs:
   test-trigger:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         actions: write
      steps:
         - 
            name: Add hosts to /etc/hosts
            run: |
              sudo echo "${{ secrets.TYK_DASHBOARD_URL }} tyk-dashboard.org" | sudo tee -a /etc/hosts 
         -
            name: Checkout
            uses: actions/checkout@v4

         -
            uses: octokit/request-action@v2.x
            id: workflow_dispatch_action
            with:
               route: POST /repos/caroltyk/tyk-apiops-demo/workflows/trigger/dispatch
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         -
            run: "echo latest release: '${{ steps.workflow_dispatch_action.outputs.data }}'"